import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { OutfitStyle } from "../types";

const MODEL_NAME = 'gemini-2.5-flash-image';
const VIDEO_MODEL_NAME = 'veo-3.1-fast-generate-preview';

/**
 * Encodes a File object to a base64 string.
 */
export const fileToGenerativePart = async (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = reader.result as string;
      // Remove the data URL prefix (e.g., "data:image/jpeg;base64,")
      const base64Data = base64String.split(',')[1];
      resolve(base64Data);
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
};

/**
 * Extracts the image data from a Gemini response.
 * It looks for an inlineData part first.
 */
const extractImageFromResponse = (response: GenerateContentResponse): string | null => {
  if (!response.candidates || response.candidates.length === 0) return null;
  
  const content = response.candidates[0].content;
  if (!content || !content.parts) return null;

  // Iterate through parts to find the image
  for (const part of content.parts) {
    if (part.inlineData && part.inlineData.data) {
      return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
    }
  }
  return null;
};

/**
 * Generates an outfit based on the uploaded item and a specific style.
 */
export const generateOutfit = async (imageBase64: string, style: OutfitStyle): Promise<string> => {
  // Always create a new instance to ensure we use the latest key if it changed
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

  const prompt = `
    Act as a professional high-end fashion stylist.
    I have provided an image of a clothing item.
    Create a complete, stylish ${style} outfit that features this item as the centerpiece.
    Generate a high-quality, photorealistic "flat-lay" style image of the entire outfit arranged neatly on a neutral, clean background.
    Ensure the lighting is soft and professional.
    The output must be an image.
  `;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/jpeg', // Assuming jpeg for simplicity, but could be png
              data: imageBase64
            }
          },
          { text: prompt }
        ]
      }
    });

    const imageUrl = extractImageFromResponse(response);
    if (!imageUrl) {
      throw new Error("No image generated by the model.");
    }
    return imageUrl;
  } catch (error) {
    console.error("Error generating outfit:", error);
    throw error;
  }
};

/**
 * Edits an existing image based on a text prompt.
 */
export const editImage = async (imageBase64: string, instruction: string): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

  // For image editing, we provide the image and the instruction.
  // The prompt should be direct for the best results with 2.5 Flash Image.
  const prompt = `Edit this image: ${instruction}. Maintain the high quality and photorealistic style.`;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'image/png', // Using generic png assumption for base64 passed around
              data: imageBase64
            }
          },
          { text: prompt }
        ]
      }
    });

    const imageUrl = extractImageFromResponse(response);
    if (!imageUrl) {
      throw new Error("No image generated by the model.");
    }
    return imageUrl;
  } catch (error) {
    console.error("Error editing image:", error);
    throw error;
  }
};

/**
 * Generates an image of a model wearing the outfit.
 */
export const generateModelLook = async (imageBase64: string): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  const prompt = `
    Based on this image of an outfit, generate a high-fashion photo of a model wearing it.
    The model should have a natural pose, standing, suitable for a fashion lookbook.
    Maintain the colors and textures of the clothing items accurately.
    Background should be a simple, elegant studio setting.
  `;

  try {
    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: {
        parts: [
          {
            inlineData: { mimeType: 'image/png', data: imageBase64 }
          },
          { text: prompt }
        ]
      }
    });

    const imageUrl = extractImageFromResponse(response);
    if (!imageUrl) {
      throw new Error("No image generated by the model.");
    }
    return imageUrl;
  } catch (error) {
    console.error("Error generating model look:", error);
    throw error;
  }
};

/**
 * Generates a video of a model walking in the outfit using Veo.
 */
export const generateRunwayVideo = async (imageBase64: string): Promise<string> => {
  // 1. Mandatory API Key Selection for Veo
  if (window.aistudio && window.aistudio.hasSelectedApiKey) {
    const hasKey = await window.aistudio.hasSelectedApiKey();
    if (!hasKey) {
      await window.aistudio.openSelectKey();
      // We assume the user selected a key successfully and proceed.
    }
  }

  // 2. Initialize AI with the (potentially new) key
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

  try {
    // 3. Start Video Generation
    let operation = await ai.models.generateVideos({
      model: VIDEO_MODEL_NAME,
      prompt: 'A professional fashion model wearing this exact outfit walking down a fashion runway. Front view, confident walk. Cinematic lighting, 4k, slow motion. High fashion.',
      image: {
        imageBytes: imageBase64,
        mimeType: 'image/png',
      },
      config: {
        numberOfVideos: 1,
        resolution: '720p',
        aspectRatio: '9:16'
      }
    });

    // 4. Poll for completion
    while (!operation.done) {
      await new Promise(resolve => setTimeout(resolve, 5000)); // Wait 5 seconds
      operation = await ai.operations.getVideosOperation({ operation: operation });
    }

    // 5. Retrieve Video
    const videoUri = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!videoUri) {
      throw new Error("Video generation completed but no URI returned.");
    }

    // 6. Fetch the video blob using the API key
    const response = await fetch(`${videoUri}&key=${process.env.API_KEY}`);
    if (!response.ok) {
      throw new Error(`Failed to download video: ${response.statusText}`);
    }
    const blob = await response.blob();
    
    // 7. Create a local object URL
    return URL.createObjectURL(blob);

  } catch (error) {
    console.error("Error generating runway video:", error);
    throw error;
  }
};